---
development:
  cloud_name: siforlat
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRRET'] %>
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: siforlat
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRRET'] %>
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: siforlat
  api_key: <%= ENV['CLOUDINARY_API_KEY'] %>
  api_secret: <%= ENV['CLOUDINARY_API_SECRRET'] %>
  enhance_image_tag: true
  static_image_support: false
